# Generated by Django 4.2.7 on 2025-09-18 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='toppings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
