# Generated by Django 4.2.7 on 2025-09-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_item_toppings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_money',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=13),
        ),
    ]
