# Generated by Django 5.1.15 on 2025-12-08 07:25

import apps.orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=apps.orders.models.get_vietnam_time)),
                ('total_before_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_after_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_money', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('order_status', models.CharField(choices=[('Chờ xác nhận', 'Chờ xác nhận'), ('Đã xác nhận', 'Đã xác nhận'), ('Đang chuẩn bị', 'Đang chuẩn bị'), ('Sẵn sàng', 'Sẵn sàng'), ('Đã lấy hàng', 'Đã lấy hàng'), ('Đã giao', 'Đã giao'), ('Đã huỷ', 'Đã huỷ')], default='Chờ xác nhận', max_length=30)),
                ('delivery_status', models.CharField(choices=[('Chờ xác nhận', 'Chờ xác nhận'), ('Đã xác nhận', 'Đã xác nhận'), ('Đã lấy hàng', 'Đã lấy hàng'), ('Đang giao', 'Đang giao'), ('Đã huỷ', 'Đã huỷ')], default='Chờ xác nhận', max_length=30)),
                ('note', models.CharField(blank=True, max_length=50)),
                ('payment_method', models.CharField(default='COD', max_length=20)),
                ('receiver_name', models.CharField(max_length=50)),
                ('ship_address', models.CharField(max_length=100)),
                ('ship_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('ship_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('route_polyline', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=10)),
                ('cancel_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('cancelled_date', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by_role', models.CharField(blank=True, choices=[('Khách hàng', 'Khách hàng'), ('Cửa hàng', 'Cửa hàng'), ('Quản lý', 'Quản lý')], max_length=20, null=True)),
                ('group_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('food_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('food_note', models.CharField(blank=True, max_length=255, null=True)),
                ('food_option_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'order_detail',
            },
        ),
    ]
