# Generated by Django 5.1.12 on 2025-10-08 19:22

import apps.orders.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('promotions', '__first__'),
        ('shipper', '__first__'),
        ('stores', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=apps.orders.models.get_vietnam_time)),
                ('total_before_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_after_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_money', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('order_status', models.CharField(choices=[('Chờ xác nhận', 'Chờ xác nhận'), ('Đã xác nhận', 'Đã xác nhận'), ('Đang chuẩn bị', 'Đang chuẩn bị'), ('Sẵn sàng', 'Sẵn sàng'), ('Đã lấy hàng', 'Đã lấy hàng'), ('Đã giao', 'Đã giao'), ('Đã huỷ', 'Đã huỷ')], default='Chờ xác nhận', max_length=30)),
                ('delivery_status', models.CharField(choices=[('Chờ xác nhận', 'Chờ xác nhận'), ('Đã xác nhận', 'Đã xác nhận'), ('Đã lấy hàng', 'Đã lấy hàng'), ('Đang giao', 'Đang giao'), ('Đã huỷ', 'Đã huỷ')], default='Chờ xác nhận', max_length=30)),
                ('note', models.CharField(blank=True, max_length=50)),
                ('payment_method', models.CharField(default='COD', max_length=20)),
                ('receiver_name', models.CharField(max_length=50)),
                ('ship_address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
                ('cancel_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('cancelled_date', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by_role', models.CharField(blank=True, choices=[('Khách hàng', 'Khách hàng'), ('Cửa hàng', 'Cửa hàng'), ('Quản lý', 'Quản lý')], max_length=20, null=True)),
                ('group_id', models.IntegerField(blank=True, null=True)),
                ('promo', models.ForeignKey(blank=True, db_column='promo_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_orders', to='promotions.promo')),
                ('promotions', models.ManyToManyField(blank=True, related_name='orders', to='promotions.promo')),
                ('shipper', models.ForeignKey(blank=True, db_column='shipper_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipper.shipper')),
                ('store', models.ForeignKey(blank=True, db_column='store_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('food_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('food_note', models.CharField(blank=True, max_length=255, null=True)),
                ('food_option_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('food', models.ForeignKey(db_column='food_id', on_delete=django.db.models.deletion.CASCADE, to='menu.food')),
                ('food_option', models.ForeignKey(blank=True, db_column='food_option_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.foodsize')),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='orders.order')),
            ],
            options={
                'db_table': 'order_detail',
            },
        ),
    ]
