# Generated by Django 4.2.7 on 2025-08-10 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promotions', '0001_initial'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('total_money', models.DecimalField(decimal_places=0, max_digits=10)),
                ('order_status', models.CharField(default='Chờ xác nhận', max_length=30)),
                ('note', models.CharField(blank=True, max_length=50)),
                ('payment_method', models.CharField(default='COD', max_length=20)),
                ('receiver_name', models.CharField(max_length=50)),
                ('ship_address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
                ('promo', models.ForeignKey(blank=True, db_column='promo_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='promotions.promo')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('food', models.ForeignKey(db_column='food_id', on_delete=django.db.models.deletion.CASCADE, to='menu.food')),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'db_table': 'order_detail',
                'unique_together': {('order', 'food')},
            },
        ),
    ]
