# Generated by Django 4.2.7 on 2025-09-04 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shipper', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promotions', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promo',
            field=models.ForeignKey(blank=True, db_column='promo_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_orders', to='promotions.promo'),
        ),
        migrations.AddField(
            model_name='order',
            name='promotions',
            field=models.ManyToManyField(blank=True, related_name='orders', through='promotions.OrderPromo', to='promotions.promo'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipper',
            field=models.ForeignKey(blank=True, db_column='shipper_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipper.shipper'),
        ),
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.ForeignKey(blank=True, db_column='store_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]