# Generated by Django 5.1.15 on 2025-12-08 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('orders', '0001_initial'),
        ('promotions', '0001_initial'),
        ('shipper', '__first__'),
        ('stores', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promo',
            field=models.ForeignKey(blank=True, db_column='promo_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_orders', to='promotions.promo'),
        ),
        migrations.AddField(
            model_name='order',
            name='promotions',
            field=models.ManyToManyField(blank=True, related_name='orders', to='promotions.promo'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipper',
            field=models.ForeignKey(blank=True, db_column='shipper_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipper.shipper'),
        ),
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.ForeignKey(blank=True, db_column='store_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='food',
            field=models.ForeignKey(db_column='food_id', on_delete=django.db.models.deletion.CASCADE, to='menu.food'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='food_option',
            field=models.ForeignKey(blank=True, db_column='food_option_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.foodsize'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='orders.order'),
        ),
    ]
