# Generated by Django 5.1.12 on 2025-10-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('promotions', '0002_orderpromo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='promotions',
            field=models.ManyToManyField(blank=True, related_name='orders', through='promotions.OrderPromo', to='promotions.promo'),
        ),
    ]
