# Generated by Django 4.2.7 on 2025-09-18 11:53

import apps.orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(default=apps.orders.models.get_vietnam_time),
        ),
    ]
