# Generated by Django 4.2.7 on 2025-09-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_orderdetail_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancelled_by_role',
            field=models.CharField(blank=True, choices=[('Khách hàng', 'Khách hàng'), ('Cửa hàng', 'Cửa hàng'), ('Quản lý', 'Quản lý')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
