# Generated by Django 4.2.7 on 2025-11-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_ship_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='route_polyline',
            field=models.TextField(blank=True, null=True),
        ),
    ]
