# Generated by Django 4.2.7 on 2025-12-24 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_add_proof_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('Chờ xác nhận', 'Chờ xác nhận'), ('Đã xác nhận', 'Đã xác nhận'), ('Đã lấy hàng', 'Đã lấy hàng'), ('Đang giao', 'Đang giao'), ('Đã giao', 'Đã giao'), ('Đã huỷ', 'Đã huỷ')], default='Chờ xác nhận', max_length=30),
        ),
    ]
