# Generated by Django 4.2.7 on 2025-09-06 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='is_topping',
        ),
    ]