# Generated by Django 4.2.7 on 2025-08-17 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
        ('menu', '0004_remove_food_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='store',
            field=models.ForeignKey(blank=True, db_column='store_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='stores.store'),
        ),
    ]
