# Generated by Django 4.2.7 on 2025-09-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_options'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE users ADD COLUMN is_shipper_registered BOOLEAN DEFAULT NULL;",
            reverse_sql="ALTER TABLE users DROP COLUMN is_shipper_registered;"
        ),
        migrations.RunSQL(
            "ALTER TABLE users ADD COLUMN is_store_registered BOOLEAN DEFAULT NULL;",
            reverse_sql="ALTER TABLE users DROP COLUMN is_store_registered;"
        ),
    ]
