# Generated by Django 4.2.7 on 2025-08-10 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_is_active_alter_user_is_staff_and_more'),
        ('authentication', '0004_add_missing_sql_fields'),
    ]

    operations = [
    ]
