# Generated by Django 4.2.7 on 2025-08-10 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_merge_20250810_2233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
