# Generated by Django 4.2.7 on 2025-08-10 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('percent', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('minimum_pay', models.FloatField()),
            ],
            options={
                'db_table': 'promo',
            },
        ),
    ]
