# Generated by Django 5.1.12 on 2025-10-08 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('scope', models.CharField(choices=[('STORE', 'Store'), ('GLOBAL', 'Global')], default='STORE', max_length=10)),
                ('discount_type', models.CharField(choices=[('PERCENT', 'Percentage'), ('AMOUNT', 'Amount')], default='PERCENT', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('minimum_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('store', models.ForeignKey(blank=True, db_column='store_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
            ],
            options={
                'db_table': 'promo',
            },
        ),
    ]
