# Generated by Django 4.2.7 on 2025-09-04 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('scope', models.CharField(choices=[('STORE', 'Store'), ('GLOBAL', 'Global')], default='STORE', max_length=10)),
                ('discount_type', models.CharField(choices=[('PERCENT', 'Percentage'), ('AMOUNT', 'Amount')], default='PERCENT', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('minimum_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('store', models.ForeignKey(blank=True, db_column='store_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
            ],
            options={
                'db_table': 'promo',
            },
        ),
        migrations.CreateModel(
            name='OrderPromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.promo')),
            ],
            options={
                'db_table': 'order_promo',
                'managed': True,
                'unique_together': {('order', 'promo')},
            },
        ),
    ]
