# Generated by Django 5.1.12 on 2025-10-08 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.promo')),
            ],
            options={
                'db_table': 'order_promo',
                'managed': True,
                'unique_together': {('order', 'promo')},
            },
        ),
    ]
