# Generated by Django 4.2.7 on 2025-09-04 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], db_column='point')),
                ('content', models.TextField(blank=True)),
                ('food', models.ForeignKey(db_column='food_id', on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='menu.food')),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rating_food',
                'unique_together': {('user', 'food', 'order')},
            },
        ),
    ]
