# Generated by Django 4.2.7 on 2025-08-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
                ('image', models.TextField(blank=True, help_text='URL path to store image (e.g., assets/store1.png)')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'stores',
            },
        ),
    ]
