# Generated by Django 4.2.7 on 2025-09-04 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
                ('image', models.TextField(blank=True, help_text='URL path to store image (e.g., assets/store1.png)')),
                ('description', models.TextField(blank=True)),
                ('manager', models.OneToOneField(blank=True, db_column='user_id', help_text='Store manager user (role_id = 3)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_store', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stores',
            },
        ),
    ]