# Generated by Django 4.2.7 on 2025-11-18 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_address_latitude_longitude'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE stores
                ADD COLUMN IF NOT EXISTS latitude NUMERIC(9, 6)
            """,
            reverse_sql="""
                ALTER TABLE stores
                DROP COLUMN IF EXISTS latitude
            """,
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE stores
                ADD COLUMN IF NOT EXISTS longitude NUMERIC(9, 6)
            """,
            reverse_sql="""
                ALTER TABLE stores
                DROP COLUMN IF EXISTS longitude
            """,
        ),
    ]
