# Generated by Django 4.2.7 on 2025-12-20 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_add_lat_long_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=10000000, max_digits=12),
        ),
    ]
